//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.24 at 12:47:43 PM CAT 
//


package sars.pca.app.dto.letter;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RequestOperation" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Details"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Detail"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element ref="{http://www.sars.gov.za/enterpriseMessagingModel/GeneratePDFDocument/xml/schemas/}GeneratePDFDocument"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requestOperation",
    "details"
})
@XmlRootElement(name = "PDFDocumentGenerationManagementRequest")
public class PDFDocumentGenerationManagementRequest {

    @XmlElement(name = "RequestOperation", required = true)
    protected String requestOperation;
    @XmlElement(name = "Details", required = true)
    protected PDFDocumentGenerationManagementRequest.Details details;
    @XmlAttribute(name = "xmlns:xsi")
    protected String xmlnsXsi;
    @XmlAttribute(name = "xmlns:xsd")
    protected String xmlnsXsd;
    @XmlAttribute(name = "xmlns")
    protected String xmlns;
    
    /**
     * Gets the value of the xmlns property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlns() {
        return xmlns;
    }

    /**
     * Sets the value of the xmlns property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlns(String value) {
        this.xmlns = value;
    }

    /**
     * Gets the value of the requestOperation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestOperation() {
        return requestOperation;
    }

    /**
     * Sets the value of the requestOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestOperation(String value) {
        this.requestOperation = value;
    }

    /**
     * Gets the value of the details property.
     * 
     * @return
     *     possible object is
     *     {@link PDFDocumentGenerationManagementRequest.Details }
     *     
     */
    public PDFDocumentGenerationManagementRequest.Details getDetails() {
        return details;
    }

    /**
     * Sets the value of the details property.
     * 
     * @param value
     *     allowed object is
     *     {@link PDFDocumentGenerationManagementRequest.Details }
     *     
     */
    public void setDetails(PDFDocumentGenerationManagementRequest.Details value) {
        this.details = value;
    }
    
     /**
     * Gets the value of the xmlnsXsi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlnsXsi() {
        return xmlnsXsi;
    }

    /**
     * Sets the value of the xmlnsXsi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlnsXsi(String value) {
        this.xmlnsXsi = value;
    }

    /**
     * Gets the value of the xmlnsXsd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlnsXsd() {
        return xmlnsXsd;
    }

    /**
     * Sets the value of the xmlnsXsd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlnsXsd(String value) {
        this.xmlnsXsd = value;
    }
    
    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Detail"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element ref="{http://www.sars.gov.za/enterpriseMessagingModel/GeneratePDFDocument/xml/schemas/}GeneratePDFDocument"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "detail"
    })
    public static class Details {

        @XmlElement(name = "Detail", required = true)
        protected PDFDocumentGenerationManagementRequest.Details.Detail detail;

        /**
         * Gets the value of the detail property.
         * 
         * @return
         *     possible object is
         *     {@link PDFDocumentGenerationManagementRequest.Details.Detail }
         *     
         */
        public PDFDocumentGenerationManagementRequest.Details.Detail getDetail() {
            return detail;
        }

        /**
         * Sets the value of the detail property.
         * 
         * @param value
         *     allowed object is
         *     {@link PDFDocumentGenerationManagementRequest.Details.Detail }
         *     
         */
        public void setDetail(PDFDocumentGenerationManagementRequest.Details.Detail value) {
            this.detail = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element ref="{http://www.sars.gov.za/enterpriseMessagingModel/GeneratePDFDocument/xml/schemas/}GeneratePDFDocument"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "generatePDFDocument"
        })
        public static class Detail {

            @XmlElement(name = "GeneratePDFDocument", required = true)
            protected GeneratePDFDocument generatePDFDocument;

            /**
             * Gets the value of the generatePDFDocument property.
             * 
             * @return
             *     possible object is
             *     {@link GeneratePDFDocument }
             *     
             */
            public GeneratePDFDocument getGeneratePDFDocument() {
                return generatePDFDocument;
            }

            /**
             * Sets the value of the generatePDFDocument property.
             * 
             * @param value
             *     allowed object is
             *     {@link GeneratePDFDocument }
             *     
             */
            public void setGeneratePDFDocument(GeneratePDFDocument value) {
                this.generatePDFDocument = value;
            }

        }

    }

}
